### ISSUE TITLE
Add MIT license?

### ISSUE THREAD

**Issue by chamaoskurumi** [patperu/fisbroker_data#1]
Hi @patperu,

your code for downloading Berlin's Fisbroker data works like a charm. :bow: 
I would like to use your code in a project, but this repo does not have a License. 

I noticed that you usually upload your work here with an an _MIT_ license, like you did [here](https://github.com/patperu/brw/blob/master/LICENSE) for example. 

Would you mind adding the same _MIT_ licence also to this repo here please? :pray: 

Best from Berlin

**Comment by patperu** [comment]
Sure thing. You might be interested in this blog post about using WFS services in R https://inbo.github.io/tutorials/tutorials/spatial_wfs_services/
